@backend_HostAddress = http://localhost:5237

// SUCCESSFUL, Should get all assignments
GET {{backend_HostAddress}}/Assignment
###

// SUCCESSFUL, Should get a specific assignment
GET {{backend_HostAddress}}/Assignment/6
###

// Should create a assignment according to THIS JSON data
POST {{backend_HostAddress}}/Assignment
Content-Type: application/json

{
  "Name": "Assignment 222",
  "Score": 0,
  "MaxScore": 100,
  "Weighting": 50,
  "CourseId": 1,
  "DueDate": "2021-12-31T23:59:59"
}
###

// Should update a assignment according to THIS JSON data
PUT {{backend_HostAddress}}/Assignment/7
###

// SUCCESSFUL, Should delete a assignment
DELETE {{backend_HostAddress}}/Assignment/5
###