// SUCCESSFUL, Should get all assignments
GET http://localhost:5237/Assignment
###

// SUCCESSFUL, Should get a specific assignment
GET http://localhost:5237/Assignment/6
###

// Should create a assignment according to THIS JSON data
POST http://localhost:5237/Assignment
###

// Should update a assignment according to THIS JSON data
PUT http://localhost:5237/Assignment/7
###

// SUCCESSFUL, Should delete a assignment
DELETE http://localhost:5237/Assignment/5
###